#store to properties file
#Sun May 03 00:45:51 IRDT 2020
numberOfTreads=10
newsagencies=entekhab

entekhab.name=انتخاب
entekhab.topic=همه
entekhab.posite=true
entekhab.seperateddatetime=false
entekhab.publisheddatetime=//*[@id="news"]/div[2]/div/div/div/div/div[1]/div[1]/div[1]/div/div[2]
entekhab.title=//*[@id="news"]/div[2]/div/div/div/div/div[1]/div[2]/div[2]/h1/a
entekhab.description=//*[@id="news"]/div[2]/div/div/div/div/div[1]/div[2]/div[3]/div[1]
entekhab.content=//*[@id="news"]/div[2]/div/div/div/div/div[1]/div[3]/div[1]
entekhab.firstpage=https://www.entekhab.ir
entekhab.samplepage=https://www.entekhab.ir/fa/news/563264/بلایی-که-ترامپ-می‌خواهد-سر-بایدن-بیاورد-تاکتیکی-که-در-شکست-هیلاری-کلینتون-موثر-بود