#store to properties file
#Sun May 03 00:45:51 IRDT 2020
numberOfTreads=10
newsagencies=isna
# isna.
isna.name=ایسنا
isna.topic=همه
isna.posite=true
isna.publisheddatetime=//*[@id="item"]/div[1]/div/ul/li[1]/span[2]
isna.title=//*[@id="item"]/div[2]/div[1]/header/div/h1
isna.description=//*[@id="item"]/div[2]/div[1]/div[1]/p
isna.content=//*[@id="item"]/div[2]/div[1]/div[1]/div
isna.firstpage=https://www.isna.ir/
isna.samplepage=https://www.isna.ir/news/99032012744/%D8%AA%D8%BA%DB%8C%DB%8C%D8%B1-%D9%82%DB%8C%D9%85%D8%AA-%D9%87%D8%A7-%D8%AF%D8%B1-%D8%A8%D8%A7%D8%B2%D8%A7%D8%B1-%D8%B3%DA%A9%D9%87-%D8%B7%D9%84%D8%A7-%D9%88-%D8%A7%D8%B1%D8%B2