#store to properties file
#Sun May 03 00:45:51 IRDT 2020
numberOfTreads=10
newsagencies=isna,varzesh3,tabnak,irna,jamejam,ilna,fars,tasnim
# isna.
isna.name=ایسنا
isna.topic=همه
isna.posite=true
isna.publisheddatetime=//*[@id="item"]/div[1]/div/ul/li[1]/span[2]
isna.title=//*[@id="item"]/div[2]/div[1]/header/div/h1
isna.description=//*[@id="item"]/div[2]/div[1]/div[1]/p
isna.content=//*[@id="item"]/div[2]/div[1]/div[1]/div
isna.firstpage=https://www.isna.ir/
isna.samplepage=https://www.isna.ir/news/99032012744/%D8%AA%D8%BA%DB%8C%DB%8C%D8%B1-%D9%82%DB%8C%D9%85%D8%AA-%D9%87%D8%A7-%D8%AF%D8%B1-%D8%A8%D8%A7%D8%B2%D8%A7%D8%B1-%D8%B3%DA%A9%D9%87-%D8%B7%D9%84%D8%A7-%D9%88-%D8%A7%D8%B1%D8%B2
# varzesh3.
varzesh3.name=ورزش3
varzesh3.topic=ورزشی
varzesh3.posite=true
varzesh3.seperateddatetime=true
varzesh3.publisheddate=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[2]/div/span[3]
varzesh3.publishedtime=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[2]/div/span[2]
varzesh3.title=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[2]/h1
varzesh3.description=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[2]/p
varzesh3.content=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[4]
varzesh3.firstpage=https://www.varzesh3.com
varzesh3.samplepage=https://www.varzesh3.com/news/1696809/%D8%A7%DB%8C%DA%AF%D9%88%D8%A7%DB%8C%D9%86-%D8%A8%D8%A7%DB%8C%D8%AF-%D9%85%D8%AB%D9%84-%D8%B2%D9%84%D8%A7%D8%AA%D8%A7%D9%86-%D8%A8%D8%A7%D8%B4%D8%AF-%D9%88-%DA%A9%D9%85-%D8%AA%D8%B1-%DA%AF%D8%B1%DB%8C%D9%87-%DA%A9%D9%86%D8%AF
# tabnak.
tabnak.name=تابناک
tabnak.topic=همه
tabnak.posite=true
tabnak.seperateddatetime=false
tabnak.publisheddatetime=//*[@id="news"]/div[2]/div/div[3]/div[3]/div/div[2]/div/sapn
tabnak.title=//*[@id="news"]/div[2]/div/div[3]/div[2]/div[2]/h1/a
tabnak.description=//*[@id="news"]/div[2]/div/div[3]/div[2]/div[3]
tabnak.content=//*[@id="news"]/div[2]/div/div[3]/div[4]
tabnak.firstpage=https://www.tabnak.ir
tabnak.samplepage=https://www.tabnak.ir/fa/news/991300/%D9%88%D8%B1%D9%88%D8%AF-%D8%AA%D9%88%DB%8C%DB%8C%D8%AA%D8%B1%DB%8C-%D9%86%D9%85%D8%A7%DB%8C%D9%86%D8%AF%DA%AF%D8%A7%D9%86-%D8%A8%D9%87-%D9%85%D9%86%D8%A7%D9%82%D8%B4%D9%87-%D9%82%D8%B1%D9%87-%D8%A8%D8%A7%D8%BA
# irna.   //*[@id="item"]/div[2]/div[1]/div[2]/span,//*[@id="item"]/div[2]/div[1]/div[2]/span
irna.name=ایرنا
irna.topic=همه
irna.posite=true
irna.publisheddatetime=//*[@id="item"]/div[2]/div[1]/div[1]/span
irna.title=//*[@id="item"]/div[2]/div[2]/h1/a
irna.description=//*[@id="item"]/p
irna.content=//*[@id="item"]/div[3]/div
irna.firstpage=https://www.irna.ir/
irna.samplepage=https://www.irna.ir/news/83815932/%D9%88%D8%A7%D8%B9%D8%B8%DB%8C-%D8%AC%D9%85%D9%87%D9%88%D8%B1%DB%8C%D8%AE%D9%88%D8%A7%D9%87%D8%A7%D9%86-%D8%A8%D9%87-%D9%81%DA%A9%D8%B1-%D8%B1%D9%81%D8%B9-%D9%86%DA%98%D8%A7%D8%AF%D9%BE%D8%B1%D8%B3%D8%AA%DB%8C-%D8%AF%D8%B1-%D8%A2%D9%85%D8%B1%DB%8C%DA%A9%D8%A7-%D8%A8%D8%A7%D8%B4%D9%86%D8%AF
# jamejam.
jamejam.name=جام جم
jamejam.topic=همه
jamejam.posite=true
jamejam.publisheddatetime=//*[@id="news"]/section[2]/div/div[1]/article/section[1]/span[3]
jamejam.title=//*[@id="news"]/section[2]/div/div[1]/article/section[2]/div[1]/div[1]/h1/a
jamejam.description=//*[@id="news"]/section[2]/div/div[1]/article/section[2]/div[2]/p
jamejam.content=//*[@id="news"]/section[2]/div/div[1]/article/section[3]
jamejam.firstpage=https://jamejamonline.ir/
jamejam.samplepage=https://jamejamonline.ir/fa/news/1268571/%D8%A7%D9%86%D8%AA%D8%B5%D8%A7%D8%A8%D8%A7%D8%AA-%D8%AC%D8%AF%DB%8C%D8%AF-%D8%AF%D8%B1-%D9%82%D9%88%D9%87-%D9%82%D8%B6%D8%A7%DB%8C%DB%8C%D9%87-%D8%B5%D8%AF%D9%88%D8%B1-%D8%AD%DA%A9%D9%85-%D8%A7%D8%B9%D8%AF%D8%A7%D9%85-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%AC%D8%A7%D8%B3%D9%88%D8%B3-%D8%A7%D9%85%D8%B1%DB%8C%DA%A9%D8%A7%DB%8C%DB%8C-%DA%A9%D9%87-%D8%A8%D8%A7%D8%B9%D8%AB-%D8%AA%D8%B1%D9%88%D8%B1-%D8%B3%D8%B1%D8%AF%D8%A7%D8%B1-%D8%B3%D9%84%DB%8C%D9%85%D8%A7%D9%86%DB%8C-%D8%B4%D8%AF
# ilna.
ilna.name=ایلنا
ilna.topic=همه
ilna.posite=true
ilna.publisheddatetime=//*[@id="st-container"]/div/section/div[3]/div/div[1]/div/article/header/div[1]/time
ilna.title=//*[@id="st-container"]/div/section/div[3]/div/div[1]/div/article/header/h1/a
ilna.description=//*[@id="st-container"]/div/section/div[3]/div/div[1]/div/article/section[1]/p[1]
ilna.content=//*[@id="st-container"]/div/section/div[3]/div/div[1]/div/article/section[1]
ilna.firstpage=https://www.ilna.news
ilna.samplepage=https://www.ilna.news/%D8%A8%D8%AE%D8%B4-%D8%B3%DB%8C%D8%A7%D8%B3%DB%8C-3/935989-%D9%87%D8%B1%D8%AC%D8%A7%DB%8C-%D8%AF%D9%86%DB%8C%D8%A7-%D9%88%D8%A7%DA%A9%D8%B3%D9%86-%DA%A9%D8%B1%D9%88%D9%86%D8%A7-%DA%A9%D8%B4%D9%81-%D8%B4%D9%88%D8%AF-%D9%88%D8%A7%D8%B1%D8%AF-%DA%A9%D8%B4%D9%88%D8%B1-%D9%85%DB%8C-%DA%A9%D9%86%DB%8C%D9%85-%D8%B3%D8%A7%D8%B2%D9%85%D8%A7%D9%86-%D9%87%D8%A7%DB%8C-%D9%85%D8%B1%D8%AF%D9%85-%D9%86%D9%87%D8%A7%D8%AF-%D8%AF%D8%B1-%D9%85%D8%A8%D8%A7%D8%B1%D8%B2%D9%87-%D8%A8%D8%A7-%DA%A9%D9%88%D9%88%DB%8C%D8%AF-%D8%A8%D9%87-%D9%85%D8%B1%D8%AF%D9%85-%DA%A9%D9%85%DA%A9-%DA%A9%D9%86%D9%86%D8%AF-%D8%A7%D8%AF%D8%B9%D8%A7%DB%8C-%DA%A9%D8%B4%D9%81-%D9%88%D8%A7%DA%A9%D8%B3%D9%86-%D8%AF%D8%A7%D8%B1%D9%88%D9%87%D8%A7%DB%8C-%D8%B6%D8%AF-%DA%A9%D8%B1%D9%88%D9%86%D8%A7-%D8%B1%D8%A7-%D8%A7%D8%B2-%D9%88%D8%B2%DB%8C%D8%B1-%D8%B3%D9%88%D8%A7%D9%84-%D9%85%DB%8C-%DA%A9%D9%86%DB%8C%D9%85
# fars.
fars.name=فارس
fars.topic=همه
fars.posite=true
fars.publisheddatetime=/html/body/div[2]/main/div[2]/div/div[1]/div[1]/div[1]/div[1]/div/div[1]/div[2]
fars.title=/html/body/div[2]/main/div[2]/div/div[1]/div[1]/div[1]/div[1]/div/div[2]/div/span[2]
fars.description=/html/body/div[2]/main/div[2]/div/div[1]/div[1]/div[1]/div[1]/div/div[2]/div/p
fars.content=/html/body/div[2]/main/div[2]/div/div[1]/div[1]/div[1]/div[2]
fars.firstpage=https://farsnews.ir
fars.samplepage=https://farsnews.ir/news/13990425000474/%D8%A8%D8%B1%D8%AC%D8%A7%D9%85-%D9%88-%D8%AA%D9%81%D8%A7%D9%87%D9%85%E2%80%8C%D9%86%D8%A7%D9%85%D9%87-%D9%87%D9%85%DA%A9%D8%A7%D8%B1%DB%8C-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D9%88-%DA%86%DB%8C%D9%86-%DB%B2-%D9%85%D8%B3%DB%8C%D8%B1-%D9%85%D8%AA%D9%81%D8%A7%D9%88%D8%AA-%D8%AF%D8%B1%D8%B9%D8%B1%D8%B5%D9%87-%D8%B3%DB%8C%D8%A7%D8%B3%D8%AA-%D8%AE%D8%A7%D8%B1%D8%AC%DB%8C
# tasnim.
tasnim.name=تسنیم
tasnim.topic=همه
tasnim.posite=true
tasnim.publisheddatetime=/html/body/div[1]/main/div/section[1]/div/section[1]/article/ul/li[1]
tasnim.title=/html/body/div[1]/main/div/section[1]/div/section[1]/article/h1
tasnim.description=/html/body/div[1]/main/div/section[1]/div/section[1]/article/h3
tasnim.content=/html/body/div[1]/main/div/section[1]/div/section[1]/article/div[3]
tasnim.firstpage=https://www.tasnimnews.com
tasnim.samplepage=https://www.tasnimnews.com/fa/news/1399/04/27/2308629/%D8%B1%D9%88%D8%AD%D8%A7%D9%86%DB%8C-%D8%A7%D8%B1%D8%B2-%D9%86%D8%A7%D8%B4%DB%8C-%D8%A7%D8%B2-%D8%B5%D8%A7%D8%AF%D8%B1%D8%A7%D8%AA-%D8%BA%DB%8C%D8%B1%D9%86%D9%81%D8%AA%DB%8C-%D8%A8%D8%A7%DB%8C%D8%AF-%D8%AF%D8%B1-%D8%AE%D8%AF%D9%85%D8%AA-%D8%AA%D9%88%D9%84%DB%8C%D8%AF-%DA%A9%D8%B4%D9%88%D8%B1-%D8%A8%D8%A7%D8%B4%D8%AF