#store to properties file
#Sun May 03 00:45:51 IRDT 2020
numberOfTreads=10
newsagencies=fars
# fars.
fars.name=فارس
fars.topic=همه
fars.posite=true
fars.publisheddatetime=/html/body/div[2]/main/div[2]/div/div[1]/div[1]/div[1]/div[1]/div/div[1]/div[2]
fars.title=/html/body/div[2]/main/div[2]/div/div[1]/div[1]/div[1]/div[1]/div/div[2]/div/span[2]
fars.description=/html/body/div[2]/main/div[2]/div/div[1]/div[1]/div[1]/div[1]/div/div[2]/div/p
fars.content=/html/body/div[2]/main/div[2]/div/div[1]/div[1]/div[1]/div[2]
fars.firstpage=https://www.farsnews.ir
fars.samplepage=https://www.farsnews.ir/news/13990425000474/%D8%A8%D8%B1%D8%AC%D8%A7%D9%85-%D9%88-%D8%AA%D9%81%D8%A7%D9%87%D9%85%E2%80%8C%D9%86%D8%A7%D9%85%D9%87-%D9%87%D9%85%DA%A9%D8%A7%D8%B1%DB%8C-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D9%88-%DA%86%DB%8C%D9%86-%DB%B2-%D9%85%D8%B3%DB%8C%D8%B1-%D9%85%D8%AA%D9%81%D8%A7%D9%88%D8%AA-%D8%AF%D8%B1%D8%B9%D8%B1%D8%B5%D9%87-%D8%B3%DB%8C%D8%A7%D8%B3%D8%AA-%D8%AE%D8%A7%D8%B1%D8%AC%DB%8C