#store to properties file
#Sun May 03 00:45:51 IRDT 2020
numberOfTreads=10
newsagencies=mojnews
# mojnews.
mojnews.name=موج
mojnews.topic=همه
mojnews.posite=true
mojnews.publisheddatetime=//*[@id="news-page-content"]/article/header/div/time[1]
mojnews.title=//*[@id="news-page-content"]/article/header/h1/a
mojnews.description=//*[@id="news-page-content"]/article/div[1]/p
mojnews.content=//*[@id="content-text"]/div
mojnews.firstpage=https://www.mojnews.com
mojnews.samplepage=https://www.mojnews.com/%D8%A8%D8%AE%D8%B4-%D8%B3%DB%8C%D8%A7%D8%B3%DB%8C-3/337343-%D9%88%D8%B2%D8%A7%D8%B1%D8%AA-%D8%B5%D9%85%D8%AA-%D9%85%D8%B3%D8%A6%D9%88%D9%84-%D8%A7%DB%8C%D8%AC%D8%A7%D8%AF-%D8%A7%D9%86%D8%B6%D8%A8%D8%A7%D8%B7-%D8%AF%D8%B1-%D8%A8%D8%AE%D8%B4-%D8%B5%D8%A7%D8%AF%D8%B1%D8%A7%D8%AA-%D9%88%D8%A7%D8%B1%D8%AF%D8%A7%D8%AA-%DA%A9%D8%A7%D9%84%D8%A7-%D8%AF%D8%B1-%DA%A9%D8%B4%D9%88%D8%B1-%D8%A7%D8%B3%D8%AA#gsc.tab=0