#store to properties file
#Sun May 03 00:45:51 IRDT 2020
numberOfTreads=10
newsagencies=varzesh3,tabnak
# varzesh3.
varzesh3.name=ورزش3
varzesh3.topic=ورزشی
varzesh3.posite=true
varzesh3.seperateddatetime=true
varzesh3.publisheddate=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[2]/div/span[3]
varzesh3.publishedtime=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[2]/div/span[2]
varzesh3.title=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[2]/h1
varzesh3.description=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[2]/p
varzesh3.content=/html/body/div[2]/div/div[2]/div/div[1]/div/div/div[4]
varzesh3.firstpage=https://www.varzesh3.com
varzesh3.samplepage=https://www.varzesh3.com/news/1696809/%D8%A7%DB%8C%DA%AF%D9%88%D8%A7%DB%8C%D9%86-%D8%A8%D8%A7%DB%8C%D8%AF-%D9%85%D8%AB%D9%84-%D8%B2%D9%84%D8%A7%D8%AA%D8%A7%D9%86-%D8%A8%D8%A7%D8%B4%D8%AF-%D9%88-%DA%A9%D9%85-%D8%AA%D8%B1-%DA%AF%D8%B1%DB%8C%D9%87-%DA%A9%D9%86%D8%AF
# tabnak.
tabnak.name=تابناک
tabnak.topic=همه
tabnak.posite=true
tabnak.seperateddatetime=false
tabnak.publisheddatetime=//*[@id="news"]/div[2]/div/div[3]/div[3]/div/div[2]/div/sapn
tabnak.title=//*[@id="news"]/div[2]/div/div[3]/div[2]/div[2]/h1/a
tabnak.description=//*[@id="news"]/div[2]/div/div[3]/div[2]/div[3]
tabnak.content=//*[@id="news"]/div[2]/div/div[3]/div[4]
tabnak.firstpage=https://www.tabnak.ir
tabnak.samplepage=https://www.tabnak.ir/fa/news/991300/%D9%88%D8%B1%D9%88%D8%AF-%D8%AA%D9%88%DB%8C%DB%8C%D8%AA%D8%B1%DB%8C-%D9%86%D9%85%D8%A7%DB%8C%D9%86%D8%AF%DA%AF%D8%A7%D9%86-%D8%A8%D9%87-%D9%85%D9%86%D8%A7%D9%82%D8%B4%D9%87-%D9%82%D8%B1%D9%87-%D8%A8%D8%A7%D8%BA